/** Sets as [reps, kg], taken from the owner's workout log (latest sessions, July 2026). */
type Sets = [reps: number, kg: number][];

export const MY_PRESET = {
  name: "My preset",
  bodyweight: ["Sit Up", "Reverse Crunch"],
  exercises: {
    "Incline Dumbbell Press": [[12, 15], [10, 22.5], [10, 27.5], [8, 30]],
    "Incline Cable Flye": [[12, 10], [10, 15], [8, 20]],
    "Dumbbell Pullover": [[10, 7.5], [8, 10]],
    "Dumbbell Prone Incline Curl": [[10, 10], [4, 17.5]],
    "Barbell Curl": [[10, 25], [7, 35]],
    "Leg Extension": [[15, 50], [12, 61], [15, 85]],
    "Hack Squat": [[10, 20], [13, 20]],
    "Split Squat with Dumbbells": [[10, 5], [11, 10]],
    "Glute Builder": [[10, 20], [8, 30]],
    "Leg Curl": [[15, 50], [12, 68], [12, 77]],
    "Romanian Deadlift": [[10, 17], [10, 20]],
    "Seated Calf Raise": [[10, 20], [15, 20], [15, 20]],
    "Dumbbell Shoulder Press": [[12, 15], [10, 20], [7, 25]],
    "Lateral Raise": [[12, 5], [10, 7.5], [7, 10]],
    "Dumbbell Shrug": [[12, 25], [11, 30], [5, 35]],
    "Low Cable Triceps Extension": [[12, 26], [10, 28], [8, 33]],
    "Standing Bent-Over One-Arm Dumbbell Triceps Extension": [[15, 12.5]],
    "Sit Up": [[18, 0]],
    "Ab Crunch Machine": [[13, 47.5]],
    "Reverse Crunch": [[12, 0]],
    "Weighted Pull Ups": [[12, 0], [9, 10], [5, 15]],
    "Lying T-Bar Row": [[10, 40], [6, 50]],
    "Barbell Deadlift": [[8, 50], [8, 55]],
    "Seated Cable Rows": [[12, 39], [15, 45]],
    "Reverse Flyes": [[12, 27], [10, 36], [8, 45]],
    "Back Extension": [[8, 15]],
    "Face Pull": [[10, 11.25], [10, 13]],
  } satisfies Record<string, Sets>,
  /** In the order the log shows them being trained. */
  days: [
    {
      name: "Chest",
      exercises: [
        "Incline Dumbbell Press",
        "Incline Cable Flye",
        "Dumbbell Pullover",
        "Dumbbell Prone Incline Curl",
        "Barbell Curl",
        "Sit Up",
        "Ab Crunch Machine",
        "Reverse Crunch",
      ],
    },
    {
      name: "Legs",
      exercises: [
        "Leg Extension",
        "Hack Squat",
        "Split Squat with Dumbbells",
        "Glute Builder",
        "Leg Curl",
        "Romanian Deadlift",
        "Seated Calf Raise",
      ],
    },
    {
      name: "Shoulders",
      exercises: [
        "Dumbbell Shoulder Press",
        "Lateral Raise",
        "Dumbbell Shrug",
        "Low Cable Triceps Extension",
        "Standing Bent-Over One-Arm Dumbbell Triceps Extension",
        "Sit Up",
        "Ab Crunch Machine",
        "Reverse Crunch",
      ],
    },
    {
      name: "Back",
      exercises: [
        "Weighted Pull Ups",
        "Lying T-Bar Row",
        "Barbell Deadlift",
        "Seated Cable Rows",
        "Reverse Flyes",
        "Back Extension",
        "Face Pull",
      ],
    },
  ],
} as const;
